2022-05-26 21:21:09,681 - CarbonIntensityThread - INFO - Traceback (most recent call last):
  File "/home/lcd842/nascar/vendors/nc_carbontracker/carbontracker/emissions/intensity/intensity.py", line 72, in carbon_intensity
    carbon_intensity = fetcher.carbon_intensity(g_location, time_dur)
  File "/home/lcd842/nascar/vendors/nc_carbontracker/carbontracker/emissions/intensity/fetchers/energidataservice.py", line 19, in carbon_intensity
    ci = self._emission_current()
  File "/home/lcd842/nascar/vendors/nc_carbontracker/carbontracker/emissions/intensity/fetchers/energidataservice.py", line 46, in _emission_current
    raise exceptions.CarbonIntensityFetcherError(response.json())
carbontracker.exceptions.CarbonIntensityFetcherError: {'statusCode': 500, 'message': 'Internal server error', 'activityId': '77f2cca1-b51d-42d9-afbe-602ced36bfdb'}

